# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('composite_id', models.CharField(max_length=255)),
                ('is_deleted', models.NullBooleanField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('score', models.FloatField(default=0)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
